// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtQ8yddmBrgcN8Pmje8gfoZEy12iH4MWM',
    appId: '1:1098710139824:web:9626bc771a9d763a304c75',
    messagingSenderId: '1098710139824',
    projectId: 'loan-managment-app-7bf91',
    authDomain: 'loan-managment-app-7bf91.firebaseapp.com',
    storageBucket: 'loan-managment-app-7bf91.firebasestorage.app',
    measurementId: 'G-C4Y2DJSWC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz-uKWdu2vbR2Igy2lTGWlGRmUf1qtLP8',
    appId: '1:1098710139824:android:995cf24ae598f594304c75',
    messagingSenderId: '1098710139824',
    projectId: 'loan-managment-app-7bf91',
    storageBucket: 'loan-managment-app-7bf91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4nyZQVwG9DuU5yylcKaBQcPKKlXX8wgg',
    appId: '1:1098710139824:ios:f5d98f71faf8d977304c75',
    messagingSenderId: '1098710139824',
    projectId: 'loan-managment-app-7bf91',
    storageBucket: 'loan-managment-app-7bf91.firebasestorage.app',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4nyZQVwG9DuU5yylcKaBQcPKKlXX8wgg',
    appId: '1:1098710139824:ios:f5d98f71faf8d977304c75',
    messagingSenderId: '1098710139824',
    projectId: 'loan-managment-app-7bf91',
    storageBucket: 'loan-managment-app-7bf91.firebasestorage.app',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtQ8yddmBrgcN8Pmje8gfoZEy12iH4MWM',
    appId: '1:1098710139824:web:cff7ae673a277579304c75',
    messagingSenderId: '1098710139824',
    projectId: 'loan-managment-app-7bf91',
    authDomain: 'loan-managment-app-7bf91.firebaseapp.com',
    storageBucket: 'loan-managment-app-7bf91.firebasestorage.app',
    measurementId: 'G-9X2JT67785',
  );
}
